import {
  ArrowLeft,
  Bell,
  BellDot,
  BookUser,
  Car,
  ChevronDown,
  ChevronRight,
  CircleDot,
  CircleUser,
  ClipboardList,
  Coins,
  Eye,
  EyeOff,
  HandCoins,
  Info,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Moon,
  MoreHorizontal,
  NotebookTabs,
  Pencil,
  Plus,
  Save,
  Settings,
  Trash2,
  Undo2,
  User,
  UserCheck,
  UserRoundPlus,
  Users,
  Wallet,
  XCircle,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  undo2: Undo2,
  chevronRight: ChevronRight,
  hand: HandCoins,
  circleDot: CircleDot,
  eye: Eye,
  eyeOff: EyeOff,
  logout: LogOut,
  settings: Settings,
  bell: Bell,
  mail: Mail,
  loader2: Loader2,
  save: Save,
  arrowLeft: ArrowLeft,
  plus: Plus,
  pencil: Pencil,
  moreHorizontal: MoreHorizontal,
  layoutDashboard: LayoutDashboard,
  user: User,
  bookUser: BookUser,
  noteBookTabs: NotebookTabs,
  wallet: Wallet,
  moon: Moon,
  bellDot: BellDot,
  circleUser: CircleUser,
  users: Users,
  car: Car,
  userCheck: UserCheck,
  clipboardList: ClipboardList,
  coins: Coins,
  xCircle: XCircle,
  chevronDown: ChevronDown,
  trash2: Trash2,
  info: Info,
  uerRoundPlus: UserRoundPlus,
};
